spring:
  application:
    name: ai
  profiles:
    default: local
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    stream:
      bindings:
        quizGenerator-in-0:
          destination: achievement
          group: ai
        quizSet-out-0:
          destination: quiz-set
          group: ai
      kafka:
        binder:
          brokers: localhost:9092

openai:
  api:
    key: ${OPEN_AI_API_KEY}

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://${LOCAL_POSTGRESQL_HOST}:${LOCAL_POSTGRESQL_PORT}/${LOCAL_POSTGRESQL_DATABASE}
    username: ${LOCAL_POSTGRESQL_USERNAME}
    password: ${LOCAL_POSTGRESQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

frontend:
  url: ${LOCAL_FRONTEND_URL}
